-- 1
SELECT
    matricula,
    nome,
    to_char(dtnascimento, 'DD/MM') AS data_aniversario,
    sysdate
FROM
    funcionarios
ORDER BY
    dtnascimento;
    
    
--2
SELECT
    funcionarios.matricula,
    funcionarios.nome,
    funcionarios.cpf,
    funcionarios.admissao,
    cargos.descricao AS cargo,
    orgaos.descricao AS secretaria,
    funcionarios.dtnascimento
FROM
         funcionarios
    JOIN cargos 
        ON cargos.empresa = funcionarios.empresa
        AND cargos.cargo = funcionarios.cargo
    JOIN setores 
        ON setores.empresa = funcionarios.empresa
        AND setores.setor = funcionarios.setor
    JOIN divisoes 
        ON divisoes.empresa = setores.empresa
        AND divisoes.codigo = setores.divisao
    JOIN orgaos 
        ON orgaos.empresa = divisoes.empresa
        AND orgaos.codigo = divisoes.orgao;
--3
SELECT FUNCIONARIOS.MATRICULA,
    FUNCIONARIOS.NOME,
    FUNCIONARIOS.ADMISSAO,
    FUNCIONARIOS.DTNASCIMENTO,
    CARGOS.DESCRICAO AS CARGO,
	SYSDATE
FROM FUNCIONARIOS
JOIN CARGOS
    ON CARGOS.EMPRESA = FUNCIONARIOS.EMPRESA
    AND CARGOS.CARGO = FUNCIONARIOS.CARGO
WHERE FUNCIONARIOS.CARGO = NVL($P!{par_cargo}, FUNCIONARIOS.CARGO)
ORDER BY CARGOS.CARGO;

Select *
From Pkg_Geral.Lista_Orgaos_Sup_Setor(
In_Empresa => 1,
In_Setor => 2
);

Select Empresa, Matricula, Setor As Orgao_Base, Fnc_Busca_Lotacaosup(Empresa, Setor) As Orgao_Sup
From Funcionarios;

Select Distinct Name
From All_Source
Where Lower(Name) Like '%sup%';

--4
SELECT FUNCIONARIOS.MATRICULA,
    FUNCIONARIOS.NOME,
    FUNCIONARIOS.CPF,
    SETORES.DESCRICAO AS SETOR,
	VINCULOS.DESCRICAO AS VINCULO,
	SYSDATE
FROM FUNCIONARIOS
JOIN SETORES
    ON SETORES.EMPRESA = FUNCIONARIOS.EMPRESA
    AND SETORES.SETOR = FUNCIONARIOS.SETOR
JOIN VINCULOS
    ON VINCULOS.VINCULO = FUNCIONARIOS.VINCULO
WHERE FUNCIONARIOS.VINCULO = NVL($P!{par_vinculo}, FUNCIONARIOS.VINCULO)
ORDER BY VINCULOS.VINCULO;

--5
SELECT FUNCIONARIOS.MATRICULA,
    FUNCIONARIOS.NOME,
    DIVISOES.DESCRICAO AS UNIDADE,
    FUNCIONARIOS.ADMISSAO,
    GRAUS.DESCRICAO AS GRAU_ESCOLARIDADE,
	SYSDATE
FROM FUNCIONARIOS
JOIN SETORES
    ON SETORES.EMPRESA = FUNCIONARIOS.EMPRESA
    AND SETORES.SETOR = FUNCIONARIOS.SETOR
JOIN DIVISOES
    ON DIVISOES.EMPRESA = SETORES.EMPRESA
    AND DIVISOES.CODIGO = SETORES.DIVISAO
JOIN GRAUS
    ON GRAUS.GRAUINST = FUNCIONARIOS.GRAUINST
WHERE GRAUS.GRAUINST = NVL($P!{par_grauinst}, GRAUS.GRAUINST)
ORDER BY GRAUS.GRAUINST
;
    
-- 6
SELECT FUNCIONARIOS.MATRICULA,
    FUNCIONARIOS.NOME,
    --NVL(FUNCIONARIOS.FONE, 'Não informado') AS TELEFONE, 
    --NVL(FUNCIONARIOS.CELULAR, 'Não informado') AS CELULAR
    NVL2(FUNCIONARIOS.FONE, FUNCIONARIOS.FONE || NVL2(FUNCIONARIOS.CELULAR, ' - ' || FUNCIONARIOS.CELULAR, ''), NVL(FUNCIONARIOS.CELULAR,  ' NÃO INFORMADO')) as TELEFONE,
    TO_CHAR(TPLOGRADOURO.DESCRICAO || ' ' || logradouro.descricao || ' ' || FUNCIONARIOS.NUMERO || ' ' || BAIRRO.BAIRRO || ' ' || CIDADES.DESCRICAO) AS ENDERE
FROM FUNCIONARIOS
JOIN CIDADES
    ON CIDADES.CIDADE = FUNCIONARIOS.CIDADE
JOIN BAIRRO
    ON BAIRRO.CIDADE = FUNCIONARIOS.CIDADE
    AND BAIRRO.BAIRRO = FUNCIONARIOS.BAIRRO
JOIN LOGRADOURO
    ON LOGRADOURO.CIDADE = FUNCIONARIOS.CIDADE
    AND LOGRADOURO.LOGRADOURO = FUNCIONARIOS.LOGRADOURO
JOIN TPLOGRADOURO
    ON TPLOGRADOURO.TIPO = LOGRADOURO.TIPO
;   

--7 qual tipo de dado usar em reais?
SELECT * FROM
(
    SELECT FUNCIONARIOS.MATRICULA,
        FUNCIONARIOS.NOME,
        CALCULOS.REFERENCIA,
        CALCULOS.VALOR,
        CALCULOS.CONTA
    FROM FUNCIONARIOS
    JOIN CALCULOS
        ON CALCULOS.EMPRESA = FUNCIONARIOS.EMPRESA
        AND CALCULOS.MATRICULA = FUNCIONARIOS.MATRICULA
    JOIN TIPOFOLHA
        ON TIPOFOLHA.TIPOFOLHA = CALCULOS.TIPOFOLHA
        AND CALCULOS.CONTA BETWEEN 9000 AND 9002
) PIVOT (
    SUM(VALOR)
    FOR CONTA
    IN( 9000 AS VANTAGENS,
        9001 AS DESCONTOS,
        9002 AS LIQUIDO )
)
ORDER BY MATRICULA
;

--8 as duas consultas estão retornando muitas linhas. nao sei por onde agrupar elas para diminuir.
--data de pagamento ou referência? algumas datas de pagamento estao nulas

SELECT
    FUNCIONARIOS.MATRICULA,
    FUNCIONARIOS.NOME,
    PERIODOS.REFERENCIA AS DATA_REFERENCIA,
    NVL(TO_CHAR(PERIODOS.DTPGTO, 'dd/mm/yyyy'), 'NÃO INFORMADO' ) AS DATA_PAGAMENTO,
    NVL(TO_CHAR(FUNCIONARIOS.HRMENSAIS), 'NÃO INFORMADO' )AS CARGA_HORARIA,
    SETORES.DESCRICAO AS LOTACAO,
    BANCOS.DESCRICAO AS BANCO    
FROM FUNCIONARIOS
JOIN SETORES
    ON SETORES.EMPRESA = FUNCIONARIOS.EMPRESA
    AND SETORES.SETOR = FUNCIONARIOS.SETOR
JOIN BANCOS
    ON BANCOS.NRBANCO = FUNCIONARIOS.BCOPGTO
JOIN CALCULOS
        ON CALCULOS.EMPRESA = FUNCIONARIOS.EMPRESA
        AND CALCULOS.MATRICULA = FUNCIONARIOS.MATRICULA
JOIN TIPOFOLHA
        ON TIPOFOLHA.TIPOFOLHA = CALCULOS.TIPOFOLHA
JOIN PERIODOS
    ON PERIODOS.TIPOFOLHA = TIPOFOLHA.TIPOFOLHA
WHERE FUNCIONARIOS.MATRICULA = 1
GROUP BY (FUNCIONARIOS.MATRICULA, FUNCIONARIOS.NOME, PERIODOS.DTPGTO, PERIODOS.REFERENCIA, FUNCIONARIOS.HRMENSAIS, SETORES.DESCRICAO, BANCOS.DESCRICAO)
ORDER BY PERIODOS.REFERENCIA
;

SELECT
    FUNCIONARIOS.MATRICULA,
    FUNCIONARIOS.NOME,
    PERIODOS.REFERENCIA AS DATA_REFERENCIA,
    PERIODOS.DTPGTO AS DATA_PAGAMENTO,
    NVL(TO_CHAR(FUNCIONARIOS.HRMENSAIS), 'NÃO INFORMADO' )AS CARGA_HORARIA,
    SETORES.DESCRICAO AS LOTACAO,
    BANCOS.DESCRICAO AS BANCO    
FROM FUNCIONARIOS
JOIN SETORES
    ON SETORES.EMPRESA = FUNCIONARIOS.EMPRESA
    AND SETORES.SETOR = FUNCIONARIOS.SETOR
JOIN BANCOS
    ON BANCOS.NRBANCO = FUNCIONARIOS.BCOPGTO
JOIN EMPRESAS
    ON EMPRESAS.EMPRESA = FUNCIONARIOS.EMPRESA
JOIN PERIODOS
    ON PERIODOS.EMPRESA = EMPRESAS.EMPRESA
WHERE FUNCIONARIOS.MATRICULA = 1
GROUP BY (FUNCIONARIOS.MATRICULA, FUNCIONARIOS.NOME, PERIODOS.DTPGTO, PERIODOS.REFERENCIA, FUNCIONARIOS.HRMENSAIS, SETORES.DESCRICAO, BANCOS.DESCRICAO)
ORDER BY PERIODOS.REFERENCIA
;

--9
SELECT CONTAS.CONTA,
    CONTAS.DESCRICAO,
    CALCULOS.QTD,
    CALCULOS.VALOR
FROM CALCULOS
JOIN CONTAS
    ON CONTAS.CONTA = CALCULOS.CONTA
GROUP BY(CONTAS.CONTA,
    CONTAS.DESCRICAO,
    CALCULOS.QTD,
    CALCULOS.VALOR)
ORDER BY CONTAS.CONTA

;
SELECT * FROM CALCULOS;
;